backend/iot/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from .views import CityAPIViewset, InformationKioskAPIViewset, ParkingSpaceAPIViewset, StreetSignAPIViewset, StreetLightAPIViewset, VehicleAPIViewset, RobotAPIViewset

router = SimpleRouter()
router.register('cities', CityAPIViewset)
router.register('informationkiosks', InformationKioskAPIViewset)
router.register('parkingspaces', ParkingSpaceAPIViewset)
router.register('streetsigns', StreetSignAPIViewset)
router.register('streetlights', StreetLightAPIViewset)
router.register('vehicles', VehicleAPIViewset)
router.register('robots', RobotAPIViewset)


urlpatterns = router.urls

backend/smartCity/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('ledger.urls')),
    path('api/v1/', include('iot.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/rest-auth/', include('rest_auth.urls')),
    path('api/v1/rest-auth/registration/', include('rest_auth.registration.urls')),
    path('iot/', include('iot.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(pattern_name='iot:city_list')),
]

backend/iot/models/city.py
from django.db import models

from ledger.models import Account

class City(models.Model):
    name = models.CharField(max_length=200)
    latitude = models.FloatField(default = 0.0)
    longitude = models.FloatField(default = 0.0)
    radius = models.FloatField(default = 0.0)
    account = models.OneToOneField(Account, on_delete=models.CASCADE, editable=False)
    
    def save(self, *args, **kwargs):
        a = Account.objects.create()
        self.account = a
        super(City, self).save(*args, **kwargs)

    def __str__(self):
        return self.name  + " with account " + self.account.__str__() + " at lat " + str(self.latitude) + " and long " + str(self.longitude) + " with radius "+ str(self.radius)

backend/iot/models/devices.py
from django.db import models
from django.contrib.auth import get_user_model

from .city import  City

from ledger.models import Transaction

# ------ Input sensors --------

class InputSensor(models.Model):
    # ABSTRACT CLASS - SHOULDN'T BE INSTANTIATED
    device = models.ForeignKey('Device', on_delete=models.CASCADE)

    def __str__(self):
        return " sensor with id " + str(self.id) + " at device " + str(self.device.__str__())

class Microphone(InputSensor):
    def __str__(self):
        return " Microphone "  + super().__str__()

class Thermometer(InputSensor):
    def __str__(self):
        return " Thermometer " + super().__str__()

class CO2Meter(InputSensor):
    def __str__(self):
        return " Co2 Meter " + super().__str__()

class Camera(InputSensor):
    def __str__(self):
        return " Camera " + super().__str__()

# ------ Output sensors --------
class OutputSensor(models.Model):
    # ABSTRACT CLASS - SHOULDN'T BE INSTANTIATED
    device = models.ForeignKey('Device', on_delete=models.CASCADE)

    def __str__(self):
        return " output sensor with id " + str(self.id) + " at device " + str(self.device.__str__())

class Speaker(OutputSensor):
    audioTranscript = models.CharField(max_length= 200)
    
    def __str__(self):
        return " Speaker audio transcript " + self.audioTranscript + super().__str__()

# ------ Devices --------

class DeviceStatus(models.TextChoices):
    WORKING = 'W', 'Working'
    NOT_WORKING = 'NW', 'Not Working'
    UNDER_MAINTENANCE = 'UM', 'Under Maintenance'

class Device(models.Model):
    # ABSTRACT CLASS - SHOULDN'T BE INSTANTIATED
    latitude = models.FloatField(default = 0.0)
    longitude = models.FloatField(default = 0.0)
    status = models.CharField(max_length=2, choices=DeviceStatus.choices, default=DeviceStatus.WORKING)
    enabled = models.BooleanField(default=True)
    
    @property
    def city(self):
        cities = City.objects.all()
        city = 0
        smallest_distance = 1e15
        for city in cities:
            distance = ((city.latitude - self.latitude)**2 + (city.longitude - self.longitude)**2)**0.5
            if distance < city.radius:
                return city
        
        # if the device is not in the radius of any city, return the first city in the db
        # CORRECT THIS!
        return cities[0]

    @property
    def account(self):
        return self.city.account

    def get_name(self):
        return 'Device'

    def __str__(self):
        return self.get_name() + " at lat " + str(self.latitude) + " and long " + str(self.longitude) + " with status "+ DeviceStatus(self.status).label + " enabled " + str(self.enabled)

class StreetSign(Device):
    text = models.CharField(max_length= 200)

    def get_name(self):
        return 'Street Sign'

    def __str__(self):
        return super().__str__() + " with text " + self.text

class InformationKiosk(Device):
    
    def purchase_ticket(self, person, event):
        # The Kiosk can also support purchasing tickets for concerts and other events.
        
        # create a transaction - payer is person and receiver is city
        amount = event.price
        payer = person.account
        receiver = self.city.account
        note = " Ticket to event " + event.__str__()
        ticket_transaction = Transaction.objects.create(amount=amount, payer=payer, receiver=receiver, note=note)
        
        # try to process the transaction and return (True if was processed or False if created but still in draft mode)
        return ticket_transaction.process()
    
    def get_name(self):
        return 'Information Kiosk'

    def __str__(self):
        return "Information Kiosk " + super().__str__()

class StreetLight(Device):
    brightness = models.FloatField(default=1.0)

    def get_name(self):
        return 'Street Light'

    def __str__(self):
        return "Street Light " + super().__str__()

class Robot(Device):

    def get_name(self):
        return 'Robot'

    def __str__(self):
        return "Robot " + super().__str__()

class ParkingSpace(Device):

    fee = models.FloatField(default=0.0)
    
    def get_name(self):
        return 'Parking Space'

    def charge(self, vehicle, hours):
        # A parking space has an hourly rate which is charged
        # to the account associated with the vehicle.
        
        # create a transaction - payer is person and receiver is city
        amount = hours * self.price
        payer = vehicle.owner.account
        receiver = self.city.account
        note = " Parking fee relative to " + hours + " hours."
        parking_transaction = Transaction.objects.create(amount=amount, payer=payer, receiver=receiver, note=note)
        
        # try to process the transaction and return (True if was processed or False if created but still in draft mode)
        return parking_transaction.process()

    def __str__(self):
        return "Parking Space " + super().__str__()

class VehicleType(models.TextChoices):
    BUS = 'B', 'Bus'
    CAR = 'C', 'Car'

class Vehicle(Device):

    vehicleType = models.CharField(max_length=1, choices=VehicleType.choices, default=VehicleType.CAR)
    maximumCapacity = models.IntegerField(default=1)
    fee = models.FloatField(default=0.0)
    owner = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)

    def get_name(self):
        return 'Vehicle'

    def charge(self, person):
        # Riding in a Bus or Car is free for Visitors, 
        # but requires a fee for Residents.
        # create a transaction - payer is person and receiver is city
        amount = self.fee
        payer = person.account
        receiver = self.city.account
        note = " Transport fee"
        boarding_transaction = Transaction.objects.create(amount=amount, payer=payer, receiver=receiver, note=note)
        
        # try to process the transaction and return (True if was processed or False if created but still in draft mode)
        return boarding_transaction.process()

    def __str__(self):
        return "Parking Space " + super().__str__()

backend/iot/models/events.py
from django.db import models
from django.utils import timezone

from .devices import Microphone, Camera, Thermometer, CO2Meter


class Event(models.Model):
    # ABSTRACT CLASS - SHOULDN'T BE INSTANTIATED
    created = models.DateTimeField(auto_now_add=timezone.now())
    
    class Meta:
        ordering = ['created']

    def __str__(self):
        return " event created at " + str(self.created)

class MicrophoneEvent(Event):
    # Django-Audiofield - https://pypi.org/project/django-audiofield/
    # audio = To be implemented
    audioTranscript = models.CharField(max_length= 200)
    microphone = models.ForeignKey(Microphone, on_delete=models.CASCADE)

    def __str__(self):
        return " Microfone audio transcript " + self.audioTranscript + super().__str__()

class CameraEvent(Event):
    # ImageField https://www.geeksforgeeks.org/imagefield-django-models/
    # image = to be implemented
    imageTranscript = models.CharField(max_length= 200)
    camera = models.ForeignKey(Camera, on_delete=models.CASCADE)

    def __str__(self):
        return " Camera image transcript "+ self.imageTranscript + super().__str__()

class ThermometerEvent(Event):
    temperature = models.FloatField(default=0.0)
    thermometer = models.ForeignKey(Thermometer, on_delete=models.CASCADE)

    def __str__(self):
        return " Temperature " + str(self.temperature) + ' oC.' + super().__str__()

class CO2Event(Event):
    co2Level = models.FloatField(default=0.0)
    co2meter = models.ForeignKey(CO2Meter, on_delete=models.CASCADE)

    def __str__(self):
        return " CO2 level " + str(self.co2Level) + super().__str__()

backend/iot/models/people.py
from django.db import models
from django.core.validators import RegexValidator

class Role(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return "Role " + self.name

class Person(models.Model):
    # ABSTRACT CLASS - SHOULDN'T BE INSTANTIATED
    person_id = models.AutoField(primary_key=True)
    latitude = models.IntegerField(default = 0)
    longitude = models.IntegerField(default = 0)
    
    def __str__(self):
        return "Person at lat " + str(self.latitude) + " and long " + str(self.longitude)

class Resident(Person):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=12,null=True, validators=[RegexValidator(r'^\d{2}-\d{4}-\d{4}$')])
    role = models.ForeignKey(Role, on_delete = models.CASCADE)
    
    def __str__(self):
        return "Resident with id "+ str(self.person_id) + " name " + self.name + " with account " + self.account.__str__() + " at lat " + str(self.latitude) + " and long " + str(self.longitude)

class Visitor(Person):
    
    def __str__(self):
        return "Visitor with id " + str(self.person_id) + " at lat " + str(self.latitude) + " and long " + str(self.longitude)

backend/iot/views.py
from django.contrib.auth import get_user_model

from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from .models import City
from .models import InformationKiosk, ParkingSpace, Robot, StreetSign, StreetLight, Vehicle

from .serializers import StreetLightSerializer, StreetSignSerializer, CitySerializer, InformationKioskSerializer, ParkingSpaceSerializer, VehicleSerializer, RobotSerializer
from .permissions import IsSuperUserOrReadOnly, IsSuperUser

from django_filters.rest_framework import DjangoFilterBackend

# Create your views here.
class CityAPIViewset(viewsets.ModelViewSet):
    permission_classes = (IsSuperUserOrReadOnly,) # new
    queryset = City.objects.all()
    serializer_class = CitySerializer

class InformationKioskAPIViewset(viewsets.ModelViewSet):
    permission_classes = (IsSuperUserOrReadOnly,) # new
    queryset = InformationKiosk.objects.all()
    serializer_class = InformationKioskSerializer

    @action(detail=True)
    def purchase_ticket(self, request, pk=None):
        print(request)
        print('pk = ', pk)
        information_kiosk = self.get_object()
        if information_kiosk.purchase_ticket(request['person'], ['event']):
            return Response({'status': 'transaction processed'})
        else:
            return Response({'status': 'transaction NOT processed'})

class ParkingSpaceAPIViewset(viewsets.ModelViewSet):
    permission_classes = (IsSuperUserOrReadOnly,) # new
    queryset = ParkingSpace.objects.all()
    serializer_class = ParkingSpaceSerializer

    @action(detail=True)
    def charge(self, request, pk=None):
        parking_space = self.get_object()
        if parking_space.charge(self, request['vehicle'], request['hours']):
            return Response({'status': 'transaction processed'})
        else:
            return Response({'status': 'transaction NOT processed'})

class RobotAPIViewset(viewsets.ModelViewSet):
    permission_classes = (IsSuperUserOrReadOnly,) # new
    queryset = Robot.objects.all()
    serializer_class = RobotSerializer

class StreetSignAPIViewset(viewsets.ModelViewSet):
    permission_classes = (IsSuperUserOrReadOnly,) # new
    queryset = StreetSign.objects.all()
    serializer_class = StreetSignSerializer

class StreetLightAPIViewset(viewsets.ModelViewSet):
    permission_classes = (IsSuperUserOrReadOnly,) # new
    queryset = StreetLight.objects.all()
    serializer_class = StreetLightSerializer

class VehicleAPIViewset(viewsets.ModelViewSet):
    permission_classes = (IsSuperUserOrReadOnly,) # new
    queryset = Vehicle.objects.all()
    serializer_class = VehicleSerializer

    @action(detail=True)
    def charge(self, request, pk=None):
        vehicle = self.get_object()
        if vehicle.charge(self, request['person']):
            return Response({'status': 'transaction processed'})
        else:
            return Response({'status': 'transaction NOT processed'})

backend/iot/templates/iot/baseOLD.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'iot\style.css' %}">

</head>
<body>

<div class="topnav">
    <a class="active" href="{% url 'iot:city_list' %}">Cities</a>
    <a href="{% url 'iot:device_list' %}">Devices</a>
    <a href="{% url 'iot:resident_list' %}">Residents</a>
</div>

<div id="content">
    {% block content %}{% endblock %}
</div>

</body>
</html>

backend/iot/templates/iot/city_detail.html
{% extends "base.html" %}

{% block content %}

<h1>{{ city.name }}</h1>

<h2>Devices at {{ city.name }}</h2>

{% for device_type, device_list in device_lists.items %}

    {% if device_list %}
    <div class="row">
        <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
            <h4 class="card-title ">Devices</h4>
            <p class="card-category">{{device_type}}</p>
            </div>
            <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                <thead class=" text-primary">
                    <th>
                    Name
                    </th>
                    <th>
                    Account Balance
                    </th>
                    <th>
                    Latitude
                    </th>
                    <th>
                    Longitude
                    </th>
                </thead>
                <tbody>
                    {% for device_obj in device_list %}
                    <tr>
                    <td>
                        <a href="#">{{ device_obj.get_name }}</a>
                    </td>
                    <td>
                        $ {{ device_obj.account.balance }}
                    </td>
                    <td>
                        {{ device_obj.latitude }}
                    </td>
                    <td>
                        {{ device_obj.longitude }}
                    </td>
                    </tr>
                    {% endfor %}
                </tbody>
                </table>
            </div>
            </div>
        </div>
        </div>
    {% else %}
        <p>No {{ device_type }}.</p>
    {% endif %}

{% endfor %}

{% endblock %}

backend/iot/templates/iot/city_list.html
{% extends "base.html" %}

{% block content %}

{% if city_list %}
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title ">Cities</h4>
          <p class="card-category"> Summary of Cities</p>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table">
              <thead class=" text-primary">
                <th>
                  Name
                </th>
                <th>
                  Account Balance
                </th>
                <th>
                  Latitude
                </th>
                <th>
                  Longitude
                </th>
                <th>
                  Radius
                </th>
                <th>
                  Number of Devices
                </th>
              </thead>
              <tbody>
                {% for city in city_list %}
                <tr>
                  <td>
                    <a href="{% url 'iot:city_detail' city.id %}">{{ city.name }}</a>
                  </td>
                  <td>
                    $ {{ city.account.balance }}
                  </td>
                  <td>
                    {{ city.latitude }}
                  </td>
                  <td>
                    {{ city.longitude }}
                  </td>
                  <td>
                    {{ city.radius }}
                  </td>
                  <td class="text-primary">
                    {% if city.device_set|length > 0 %}
                        {{ city.device_set|length }}
                    {% else %}
                        No device(s)
                    {% endif %}
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
{% endif %}

{% endblock %}

backend/iot/templates/iot/device_detail.html
{% extends "base.html" %}

{% block content %}

<h1>{{ device_name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'iot:update_device' device.city_holder.accountHolder_id device.accountHolder_id %}" method="post">
{% csrf_token %}

<p><b>Latitude:</b> {{device.latitude}}</p>
<p><b>Longitude:</b> {{device.longitude}}</p>

<p>
    <b>Status:</b> {{device.status}}
    {% if device.status == status.WORKING %}
        <input type="radio" id="status_not_working" name="status" value="not working">
            <label for="status_not_working">Not Working</label>
        <input type="radio" id="status_maintenance" name="status" value="maintenance">
            <label for="status_maintenance">Under Maintenance</label>
    {% elif device.status == status.NOT_WORKING %}
        <input type="radio" id="status_working" name="status" value="working">
            <label for="status_working">Working</label>
        <input type="radio" id="status_maintenance" name="status" value="maintenance">
            <label for="status_maintenance">Under Maintenance</label>
    {% elif device.status == status.UNDER_MAINTENANCE %}
        <input type="radio" id="status_working" name="status" value="working">
            <label for="status_working">Working</label>
        <input type="radio" id="status_not_working" name="status" value="not working">
            <label for="status_not_working">Not Working</label>
    {% endif %}
</p>



<p>
    <b>Enabled:</b> {{device.enabled}}

    {% if device.enabled == False %}
        <input type="checkbox" id="enable" name="enable_disable" value="enable">
            <label for="enable">Enable</label><br>
    {% else %}
        <input type="checkbox" id="disable" name="enable_disable" value="disable">
            <label for="disable">Disable</label><br>
    {% endif %}

</p>

{% if device_name == "Street Sign" %}
<p><b>Text:</b> {{device.text}}

    <input type="text" name="streetsign_text" id="streetsign_text">

</p>

{% endif %}

{% if device_name == "Street Light" %}
<p><b>Brightness:</b> {{device.brightness}}</p>
{% endif %}

<input type="submit" value="Change">
</form>

{% endblock %}

backend/iot/templates/iot/device_list.html
{% extends "iot/base.html" %}

{% block content %}

{% if device_list %}
    <ul>
    {% for device in device_list %}
        <li><a href="{% url 'iot:device_detail' device.pk %}">{{ device }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No device registered.</p>
{% endif %}

{% endblock %}

backend/iot/templates/iot/resident_detail.html
{% extends "iot/base.html" %}

{% block content %}

<h1>{{ resident.name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'iot:resident_detail' resident.person_id %}" method="post">
{% csrf_token %}

<p><b>Latitude:</b> {{resident.latitude}}</p>
<p><b>Longitude:</b> {{resident.longitude}}</p>


<p>
    <b>Phone:</b> {{resident.phone}}
    
    <input type="text" name="phone_text" id="phone_text">
</p>

<input type="submit" value="Change">
</form>

{% endblock %}

backend/iot/templates/iot/resident_list.html
{% extends "iot/base.html" %}

{% block content %}

{% if resident_list %}
    <ul>
    {% for resident in resident_list %}
        <li><a href="{% url 'iot:resident_detail' resident.person_id %}">{{ resident.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No resident registered.</p>
{% endif %}

{% endblock %}